services:
  - type: web
    name: expense-tracker-backend
    root: backend
    buildCommand: npm install && npm run postinstall
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
